<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-JersonDavidPerezContreras/blob/main/Semana_3_Python_for_Data_Science_(IBM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Semana 3: Python for Data Science (IBM)

Jerson David Perez Contreras

In [2]:
#Numpy 1D Arrays
import numpy as np
#QUESTION 1

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [3]:
# Question 2

np.dot(np.array([1,-1]),np.array([1,1]))

0

In [5]:
#Numpy 2D Arrays

# Question 1
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#Question 2
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)  ## no ejecuta ya que ambos tiene deiferentes dimensiones

In [7]:
#Review Questions

#Pregunta 1

a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [8]:
#Pregunta 2
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [9]:
# Pregunta 3

a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [ ]:
# Pregunta 4

#np.dot para multiplicar matrices

In [10]:
# Examen final

# pregunta 1

3+2*2

7

In [11]:
# pregunt 2
type(True)

bool

In [12]:
# Pregunta 3
int(3.2)

3

In [13]:
# Pregunta 4
A='1234567'
A[1::2]

'246'

In [14]:
#Pregunta 5

Name="Michael Jackson"
Name.find('el')

5

In [15]:
#Pregunta 6
A='1'
B='2'
A+B

'12'

In [22]:
#Pregunta 7
F="You are wrong"
F= F.upper()
F

'YOU ARE WRONG'

In [23]:
# Pregunta 8
tuple1=("A","B","C" )
tuple1[-1]

'C'

In [24]:
#Pregunta 9

A=((11,12),[21,22])
A[1]

[21, 22]

In [26]:
#Pregunta 10

A=((11,12),[21,22])
A[0][1]

12

In [27]:
#Pregunta 11
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [28]:
#Pregunta 12

A=[1,'a']
B=[2,1,'d']
A+B

[1, 'a', 2, 1, 'd']

In [30]:
#pREGUNTA 13
a=set(A)
a

{1, 'a'}

In [32]:
#Pregunta 14
V={'A','B'}
V.add('C')
V

{'A', 'B', 'C'}

In [33]:
#Pregunta 15

V={'A','B','C' }
V.add('C')
V

{'A', 'B', 'C'}

In [34]:
#Pregunta 16

x="Go"

if(x!="Go"):

  print('Stop')

else:

  print('Go ')

print('Mike')



Go 
Mike


In [35]:
# Pregunta 17

x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')

Go 
Mike


In [36]:
#pregunta 18

for n in range(3):

  print(n)

0
1
2


In [37]:
# Pregunta 19

for n in range(3):

  print(n+1)

1
2
3


In [38]:
#Pregunta 20

A=['1','2','3']

for a in A:

  print(2*a)

11
22
33


In [39]:
# Pregunta 21

def Add(x,y):

  z=y+x

  return(y)
Add('1','1')

'1'

In [40]:
#Pregunta 22
class Points(object):

  def __init__(self,x,y):

    self.x=x

    self.y=y

  def print_point(self):

    print('x=',self.x,'y=',self.y)

# Atributos self.x and self.y

In [41]:
# Pregunta 23

class Points(object):

  def __init__(self,x,y):

    self.x=x

    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points(1,2)

p1.print_point()

x= 1  y= 2


In [42]:
#Pregunta 24

class Points(object):

  def __init__(self,x,y):

    self.x=x

    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x=2

p2.print_point()

x= 2  y= 2


In [ ]:
# Pregunta 25

## with open(example1,"r") as file1  aBRE EN MODO LECTURA UN ARCHIVO